apiVersion: v1
kind: Service
metadata:
  name: gogorm-service
  namespace: test-dev
spec:
  type: NodePort
  selector:
    app: gogorm
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30003
